apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-service
  labels:
    app: collector-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector-service
  template:
    metadata:
      labels:
        app: collector-service
    spec:
      containers:
        - name: collector-service
          image: highlee/collector-service:0.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
