--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.4

-- Started on 2025-07-30 19:31:55 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 17356)
-- Name: bike; Type: TABLE; Schema: public; Owner: bubiuser
--

CREATE TABLE public.bike (
    uuid character varying(255) NOT NULL
);


ALTER TABLE public.bike OWNER TO bubiuser;

--
-- TOC entry 215 (class 1259 OID 17361)
-- Name: snapshot_bike; Type: TABLE; Schema: public; Owner: bubiuser
--

CREATE TABLE public.snapshot_bike (
    snapshot_id bigint NOT NULL,
    bike_id character varying(255) NOT NULL
);


ALTER TABLE public.snapshot_bike OWNER TO bubiuser;

--
-- TOC entry 216 (class 1259 OID 17364)
-- Name: station; Type: TABLE; Schema: public; Owner: bubiuser
--

CREATE TABLE public.station (
    latitude double precision,
    longitude double precision,
    id character varying(255) NOT NULL,
    name character varying(255)
);


ALTER TABLE public.station OWNER TO bubiuser;

--
-- TOC entry 218 (class 1259 OID 17372)
-- Name: station_snapshot; Type: TABLE; Schema: public; Owner: bubiuser
--

CREATE TABLE public.station_snapshot (
    empty_slots integer,
    free_bikes integer,
    total_slots integer,
    id bigint NOT NULL,
    "timestamp" timestamp(6) with time zone,
    weather_id bigint,
    station_id character varying(255),
    station_number character varying(255),
    station_uid character varying(255)
);


ALTER TABLE public.station_snapshot OWNER TO bubiuser;

--
-- TOC entry 217 (class 1259 OID 17371)
-- Name: station_snapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: bubiuser
--

ALTER TABLE public.station_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.station_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17380)
-- Name: weather_data; Type: TABLE; Schema: public; Owner: bubiuser
--

CREATE TABLE public.weather_data (
    apparent_temperature double precision,
    cloud_cover integer,
    day boolean,
    "interval" integer,
    rain double precision,
    relative_humidity integer,
    showers double precision,
    snow_fall double precision,
    temperature double precision,
    wind_direction integer,
    wind_gusts integer,
    wind_speed integer,
    id bigint NOT NULL,
    "time" timestamp(6) without time zone,
    unit_id bigint
);


ALTER TABLE public.weather_data OWNER TO bubiuser;

--
-- TOC entry 219 (class 1259 OID 17379)
-- Name: weather_data_id_seq; Type: SEQUENCE; Schema: public; Owner: bubiuser
--

ALTER TABLE public.weather_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weather_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17388)
-- Name: weather_unit; Type: TABLE; Schema: public; Owner: bubiuser
--

CREATE TABLE public.weather_unit (
    id bigint NOT NULL,
    apparent_temperature character varying(255),
    coud_cover character varying(255),
    day character varying(255),
    "interval" character varying(255),
    rain character varying(255),
    relative_humidity character varying(255),
    showers character varying(255),
    snowfall character varying(255),
    temperature character varying(255),
    "time" character varying(255),
    wind_direction character varying(255),
    wind_gusts character varying(255),
    wind_speed character varying(255)
);


ALTER TABLE public.weather_unit OWNER TO bubiuser;

--
-- TOC entry 221 (class 1259 OID 17387)
-- Name: weather_unit_id_seq; Type: SEQUENCE; Schema: public; Owner: bubiuser
--

ALTER TABLE public.weather_unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weather_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3222 (class 2606 OID 17360)
-- Name: bike bike_pkey; Type: CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.bike
    ADD CONSTRAINT bike_pkey PRIMARY KEY (uuid);


--
-- TOC entry 3224 (class 2606 OID 17370)
-- Name: station station_pkey; Type: CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.station
    ADD CONSTRAINT station_pkey PRIMARY KEY (id);


--
-- TOC entry 3226 (class 2606 OID 17378)
-- Name: station_snapshot station_snapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.station_snapshot
    ADD CONSTRAINT station_snapshot_pkey PRIMARY KEY (id);


--
-- TOC entry 3228 (class 2606 OID 17384)
-- Name: weather_data weather_data_pkey; Type: CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.weather_data
    ADD CONSTRAINT weather_data_pkey PRIMARY KEY (id);


--
-- TOC entry 3230 (class 2606 OID 17386)
-- Name: weather_data weather_data_time_key; Type: CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.weather_data
    ADD CONSTRAINT weather_data_time_key UNIQUE ("time");


--
-- TOC entry 3232 (class 2606 OID 17394)
-- Name: weather_unit weather_unit_pkey; Type: CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.weather_unit
    ADD CONSTRAINT weather_unit_pkey PRIMARY KEY (id);


--
-- TOC entry 3237 (class 2606 OID 17415)
-- Name: weather_data fk4091r8hl5k3gk14pa93eodbbe; Type: FK CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.weather_data
    ADD CONSTRAINT fk4091r8hl5k3gk14pa93eodbbe FOREIGN KEY (unit_id) REFERENCES public.weather_unit(id);


--
-- TOC entry 3235 (class 2606 OID 17410)
-- Name: station_snapshot fk4bv9f328wrr5c1t3012pr0jr2; Type: FK CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.station_snapshot
    ADD CONSTRAINT fk4bv9f328wrr5c1t3012pr0jr2 FOREIGN KEY (weather_id) REFERENCES public.weather_data(id);


--
-- TOC entry 3233 (class 2606 OID 17395)
-- Name: snapshot_bike fk9y74ryb6rb2c85cnytg9xgctc; Type: FK CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.snapshot_bike
    ADD CONSTRAINT fk9y74ryb6rb2c85cnytg9xgctc FOREIGN KEY (bike_id) REFERENCES public.bike(uuid);


--
-- TOC entry 3234 (class 2606 OID 17400)
-- Name: snapshot_bike fkgvnm41n3y9okghddk7hxglrtx; Type: FK CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.snapshot_bike
    ADD CONSTRAINT fkgvnm41n3y9okghddk7hxglrtx FOREIGN KEY (snapshot_id) REFERENCES public.station_snapshot(id);


--
-- TOC entry 3236 (class 2606 OID 17405)
-- Name: station_snapshot fkt21wp0noc61g4cde3s4du245e; Type: FK CONSTRAINT; Schema: public; Owner: bubiuser
--

ALTER TABLE ONLY public.station_snapshot
    ADD CONSTRAINT fkt21wp0noc61g4cde3s4du245e FOREIGN KEY (station_id) REFERENCES public.station(id);


-- Completed on 2025-07-30 19:31:55 UTC

--
-- PostgreSQL database dump complete
--

