spring:
  application:
    name: persistence-service
  profiles:
    active: dev
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: schema_version
    baseline-version: 1.0.0
    baseline-description: Initial version
    out-of-order: true