apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence-service
  labels:
    app: persistence-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistence-service
  template:
    metadata:
      labels:
        app: persistence-service
    spec:
      containers:
        - name: persistence-service
          image: highlee/persistence-service:0.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: jdbc-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
